# Generated by Django 5.2.8 on 2025-11-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='rooms',
            new_name='room',
        ),
    ]
